---
- name: DEMO AN INTERACTIVE PRIVATE KEY
  hosts: localhost
  gather_facts: no
  tasks:

    - name: DISPLAY THE INJECTED EXTRA VAR
      debug:
        var: secret_key

    - name: CLONE THE GIT REPO
      git:
        repo: "ssh://git@github.com:michaelford85/ansible-aci.git"
        dest: /tmp/my_test_repo
        key_file: "{{ secret_key  }}"
      delegate_to: localhost
